### ISSUE TITLE
Delete RasmusDev Branch

### ISSUE THREAD

**Issue by Njoselson** [Njoselson/natemusMasters#12]
Hej Rasmus, 

Kan du radera din RasmusDev Branch och branch out från master igen (med fetching och pulling alla nya ändringar därifrån?) Vi jobbar så nära varandra så att det är bad practice att ha branches öppet och merga igen och igen. Mycket bättre att brancha ut varje gång man ska lägga till någonting i repo'n istället för att ha en miljon commits på samma träd med en gång.

**Comment by Programermus** [comment]
Jag förstår inte vad det där betyder nate!! Nu har jag och Sverker kommit fram till Aron! Mitt i tel aviv!

**Comment by Programermus** [comment]
Men jag kan kika lite ikväll!

**Comment by Njoselson** [comment]
Jag menar bara så att du inte gör nya jobb på rasmusDev branchen. Om du ska jobba mer (vilket jag tycker inte att du ska göra under Israelresan), så ska du skapa ett nytt branch och gör det där...

**Comment by Programermus** [comment]
Ahh ok!! Jo absolut!! Rasmusdevbranchen är väldigt stökig :D jag älskar telaviv hittills nate, det är en otrolig stad!
